/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  ActionHandler,
  Effect,
} from './components/control-provider/data/control';

export namespace Components {
  interface AppHome {}
  interface AppRoot {}
  interface ControlProvider {}
  interface DragControls {
    'dispatch': (action: ActionHandler) => void;
    'effect': Effect;
    'hue': number;
  }
  interface WhatADrag {
    'dispatch': (action: ActionHandler) => void;
    'effect': Effect;
    'hue': number;
  }
}

declare global {


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLControlProviderElement extends Components.ControlProvider, HTMLStencilElement {}
  var HTMLControlProviderElement: {
    prototype: HTMLControlProviderElement;
    new (): HTMLControlProviderElement;
  };

  interface HTMLDragControlsElement extends Components.DragControls, HTMLStencilElement {}
  var HTMLDragControlsElement: {
    prototype: HTMLDragControlsElement;
    new (): HTMLDragControlsElement;
  };

  interface HTMLWhatADragElement extends Components.WhatADrag, HTMLStencilElement {}
  var HTMLWhatADragElement: {
    prototype: HTMLWhatADragElement;
    new (): HTMLWhatADragElement;
  };
  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-root': HTMLAppRootElement;
    'control-provider': HTMLControlProviderElement;
    'drag-controls': HTMLDragControlsElement;
    'what-a-drag': HTMLWhatADragElement;
  }
}

declare namespace LocalJSX {
  interface AppHome {}
  interface AppRoot {}
  interface ControlProvider {}
  interface DragControls {
    'dispatch'?: (action: ActionHandler) => void;
    'effect'?: Effect;
    'hue'?: number;
  }
  interface WhatADrag {
    'dispatch'?: (action: ActionHandler) => void;
    'effect'?: Effect;
    'hue'?: number;
  }

  interface IntrinsicElements {
    'app-home': AppHome;
    'app-root': AppRoot;
    'control-provider': ControlProvider;
    'drag-controls': DragControls;
    'what-a-drag': WhatADrag;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-home': LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
      'control-provider': LocalJSX.ControlProvider & JSXBase.HTMLAttributes<HTMLControlProviderElement>;
      'drag-controls': LocalJSX.DragControls & JSXBase.HTMLAttributes<HTMLDragControlsElement>;
      'what-a-drag': LocalJSX.WhatADrag & JSXBase.HTMLAttributes<HTMLWhatADragElement>;
    }
  }
}


